version: '3.8'

services:
  # Base de données PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: collabhub-postgres
    environment:
      POSTGRES_DB: candidatdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks: 
      - collabhub-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d candidatdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Service Candidat (Go)
  service-candidat:
    build:
      context: ./service-candidat-go
    container_name: collabhub-service-candidat
    environment:
      DB_HOST: collabhub-postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: candidatdb
    ports: 
    - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks: 
      - collabhub-network

# Volumes persistants
volumes:
  postgres_data:
    driver: local

networks:
  collabhub-network:
    driver: bridge
